name: Deploy 🚀

on:
  pull_request:
    branches:
      - main
    types: [closed]
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: src/PrologIdle/Library
          key: Library

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: src/PrologIdle
          unityVersion: 2020.3.9f1
          targetPlatform: WebGL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: prolog-idle/prolog-idle.github.io
          branch: gh-pages
          folder: build/WebGL/WebGL
          commit-message: Export
          single-commit: true